include:
- project: $CATALOG_PATH
  file: vault-ci.yml
  ref: main
- project: $CATALOG_PATH
  file: kaniko-ci.yml
  ref: main

default:
  image: alpine:latest

stages:
- read-secret
- docker-build

read_secret:
  stage: read-secret
  extends:
  - .vault:read_secret

generate_var:
  image: ghcr.io/this-is-tobi/tools/curl:latest
  stage: read-secret
  script:
  - |
    # first use tag var then fallback to .release-please-manifest.json if tag var is not set
    if [ -n "$CI_COMMIT_TAG" ]; then
      VERSION="$CI_COMMIT_TAG"
    else
      VERSION=$(jq -r '.["."]' .release-please-manifest.json)
    fi
    echo "PATCH=$VERSION" >> vars.env
  - cat vars.env
  artifacts:
    reports:
      dotenv: vars.env

build:
  before_script:
  - echo $PATCH
  needs: [generate_var, read_secret]
  variables:
    WORKING_DIR: ./
    DOCKERFILE: ./backend/Dockerfile
    IMAGE_NAMES: server:${PATCH}
    EXTRA_BUILD_ARGS: --build-arg VERSION=${PATCH}
  stage: docker-build
  extends:
  - .kaniko:build-push
  # Triggers job only if a file in the client directory changed in current commit
  # rules:
  #   - changes:
  #     - client/**/*
