{{- if and (not .Values.app.smtp.existingSecret) (kindIs "string" .Values.app.smtp.password) (not (empty .Values.app.smtp.password)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-comu.fullname" . }}-smtp
  labels:
    {{- include "keycloak-comu.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.app.smtp.password | quote }}
{{- end }}
