apiVersion: v2
name: keycloak-comu
description: Keycloak Community - Group management application
type: application
version: 0.1.2
appVersion: "1.0.1"
maintainers:
  - name: IA-Generative
keywords:
  - keycloak
  - community
  - groups
  - oauth
