name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build, e.g. v1.2.3, if empty, latest version from package.json will be used"
        required: false
        default: ""
  workflow_call:
    inputs:
      tag:
        description: "Tag to build, e.g. v1.2.3, if empty, latest version from package.json will be used"
        required: false
        type: string
        default: ""
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_version.outputs.tags }}
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract version
      id: get_version
      run: |
        VERSION=$(jq -r .version < package.json)
        MAJOR=$(echo $VERSION | cut -d. -f1)
        MINOR=$(echo $VERSION | cut -d. -f1,2)
        echo "MAJOR=ghcr.io/ia-generative/keycloak-comu:$MAJOR" >> $GITHUB_OUTPUT
        echo "MINOR=ghcr.io/ia-generative/keycloak-comu:$MINOR" >> $GITHUB_OUTPUT
        echo "PATCH=ghcr.io/ia-generative/keycloak-comu:$VERSION" >> $GITHUB_OUTPUT
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        pull: true
        tags: |
          ${{ steps.get_version.outputs.MAJOR }}
          ${{ steps.get_version.outputs.MINOR }}
          ${{ steps.get_version.outputs.PATCH }}
