name: Build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Tag to build, e.g. v1.2.3, if empty, latest version from package.json will be used, one per line for multiple tags"
        required: false
        default: ""
  workflow_call:
    inputs:
      tags:
        description: "Tag to build, e.g. v1.2.3, if empty, latest version from package.json will be used, one per line for multiple tags"
        required: false
        type: string
        default: ""
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_version.outputs.tags }}
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract version
      id: get_version
      run: |
        if [ -n "${{ github.event.inputs.tags }}" ]; then
        {
          echo "TAGS<<EOF"
          echo "${{ github.event.inputs.tags }}"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
        else
          VERSION=$(jq -r .version < package.json)
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f1,2)
          {
            echo "TAGS<<EOF"
            echo "ghcr.io/ia-generative/keycloak-comu:$MAJOR"
            echo "ghcr.io/ia-generative/keycloak-comu:$MINOR"
            echo "ghcr.io/ia-generative/keycloak-comu:$VERSION"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        fi
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        pull: true
        tags: |
          ${{ steps.get_version.outputs.TAGS }}
