name: Build

on:
  push:
    tags:
    - "v*.*.*"
  workflow_call:
    inputs:
      tags:
        required: false
        type: string
        description: "Tags to push, separated by return line. If not provided, it will be extracted from package.json"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_version.outputs.tags }}
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract version
      id: get_version
      run: |
        if [ -z "${{ inputs.tags }}" ]; then
          echo "No tags provided, extracting from package.json"
          VERSION=$(jq -r .version < package.json)
          MAJOR="ghcr.io/ia-generative/keycloak-comu:$(echo $VERSION | cut -d. -f1)"
          MINOR="ghcr.io/ia-generative/keycloak-comu:$(echo $VERSION | cut -d. -f1,2)"
          PATCH="ghcr.io/ia-generative/keycloak-comu:$(echo $VERSION)"
          echo "tags=$MAJOR\n$MINOR\n$PATCH" >> $GITHUB_OUTPUT
        else
          echo "Using provided tags"
          TAGS=$(echo "${{ inputs.tags }}")
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
        fi
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        pull: true
        tags: |
          ${{ steps.get_version.outputs.tags }}
