name: Build

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      target:
        required: true
        type: string
  push:
    branches:
    - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_version.outputs.tags }}
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract version
      id: get_version
      run: |
        VERSION=$(jq -r .version < package.json)
        MAJOR=$(echo $VERSION | cut -d. -f1)
        MINOR=$(echo $VERSION | cut -d. -f2)
        PATCH=$(echo $VERSION | cut -d. -f3)
        echo "MAJOR=${{ inputs.image }}:$MAJOR" >> $GITHUB_OUTPUT
        echo "MINOR=${{ inputs.image }}:$MINOR" >> $GITHUB_OUTPUT
        echo "PATCH=${{ inputs.image }}:$PATCH" >> $GITHUB_OUTPUT
    - name: Get version
      id: debug
      run: |
        echo ${{ steps.get_version.outputs.MAJOR }}
    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: ${{ inputs.context }}
    #     push: true
    #     pull: true
    #     tags: ${{ steps.get_version.outputs.tags }}
    #     target: ${{ inputs.target }}
