name: Lint

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "v1.26.2"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        working-directory: backend
